### ISSUE TITLE
Review of MPS-BedMappingV1

### ISSUE THREAD

**Issue by weiji14** [sdyinzhen/MPS-BedMappingV1#1]
Hi @sdyinzhen,

Great work on your paper :smile:. I'm attaching the markdown (plaintext) version of my review comment (https://doi.org/10.5194/gmd-2021-297-RC2) here for your reference. This should hopefully save you some time with not having to copy and paste out of a PDF for the corrections step later (something I got annoyed with for my paper last year).

[gmd-2021-297-RC2.md](https://github.com/sdyinzhen/MPS-BedMappingV1/files/7282882/gmd-2021-297-RC2.md)

Let me know too if you need any clarification, or if you need help with anything. Good luck!

**Comment by sdyinzhen** [comment]
Thank you so much for your supportive comments and markdown file, Wei Ji!
We will revise the paper based on your comments :).

Best wishes,
David

**Comment by sdyinzhen** [comment]
Hi Weiji,

I just noticed that you joined my AGU live session today. Sorry I left the
Zoom session just minutes before you joined. Please let me know if you
still want to discuss. We can create a new zoom :).

Cheers,
David

**Comment by weiji14** [comment]
Oh hi @sdyinzhen, yes I woke up a bit too late (it's like 6am...) so thought you might have left already. I'm free now so will wait for you in the same Zoom meeting you created just now.

**Comment by sdyinzhen** [comment]
sounds great @weiji14. Here here is the link:  https://stanford.zoom.us/j/99416623683?pwd=Q2FGNmU5eWRsdjJyMFNwZDJQRm1UUT09   
pwd: 244083

**Comment by weiji14** [comment]
Hmm, it says the link is invalid, could you double check?

**Comment by sdyinzhen** [comment]
Sorry, some technical issues. Can we still use the AGU one?

**Comment by sdyinzhen** [comment]
In case : 
https://stanford.zoom.us/j/98871099225?pwd=ME5sd3ZRenhEYUN5cFNXaXRJZlFoUT09
pwd: 134126

**Comment by weiji14** [comment]
Cool, thanks for the chat @sdyinzhen. We'll keep in touch :smile:

**Comment by sdyinzhen** [comment]
Nice to chat with you Wei Ji. I just uploaded the DS simulation results to the repo: https://github.com/sdyinzhen/MPS-BedMappingV1/tree/main/results . Will update the notebooks accordingly.
